### ISSUE TITLE
Python version constraint

### ISSUE THREAD

**Issue by denblackstache** [lemonpaul/yandex2spotify#35]
Hi. Pretty much a flawless 1st-time experience. Thank you for the tool!

It would be useful to add a Python interpreter version constraint. The Pillow lib used in the project is not compatible with the latest Python 3.10 and 3.11.

I did an investigation and figured out Pillow 8.1.1 is compatible with Python >=3.6, <= 3.9.
See https://pillow.readthedocs.io/en/latest/installation.html#python-support

Cheers

**Comment by MarshalX** [comment]
Hi! Could you make a pull request, please? Maybe it will be enough to update versions of deps in req.txt
