### ISSUE TITLE
Exception when track name is too long

### ISSUE THREAD

**Issue by anissimov58** [lemonpaul/yandex2spotify#41]
When track name is too long (100+ characters) there is an exception happening because spotify API can not process it.

Cheap and dirty fix is to limit track name length to 100 characters

To fix this issue simply add in  _import_item check for string length and substring track name if len is more than 100

    def _import_item(self, item):
        type_ = item.__class__.__name__.casefold()
        item_name = item.name if isinstance(item, Artist) else f'{", ".join([artist.name for artist in item.artists])} '\
                                                               f'- {item.title}'

#ADD THIS ADD THIS ADD THIS ADD THIS ADD THIS ADD THIS ADD THIS

        if len(item_name)>100:
            item_name = item_name[:100]
            logger.info('Too Long Shlong')

#ADD THIS ADD THIS ADD THIS ADD THIS ADD THIS ADD THIS ADD THIS

        query = item_name.replace('- ', '')
        found_items = handle_spotify_exception(self.spotify_client.search)(query, type=type_)[f'{type_}s']['items']
        logger.info(f'Importing {type_}: {item_name}...')

        if not self._strict_search and not isinstance(item, Artist) and not len(found_items) and len(item.artists) > 1:
            query = f'{item.artists[0]} {item.title}'
            found_items = handle_spotify_exception(self.spotify_client.search)(query, type=type_)[f'{type_}s']['items']

        logger.info(f'Searching "{query}"...')

        if not len(found_items):
            raise NotFoundException(item_name)

        return found_items[0]['id']

**Comment by MarshalX** [comment]
Hi, Could you make pull request, please?

**Comment by anissimov58** [comment]
Done 
https://github.com/lemonpaul/yandex2spotify/pull/44

**Comment by MarshalX** [comment]
Thank you!
