### ISSUE TITLE
ERROR - An unexpected error occurred: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Reagent992** [lemonpaul/yandex2spotify#52]
Спасибо за классный скрипт.
Скопировал почти всю библиотеку.
При копирование возникла ошибка:

![Screenshot 2023-11-10 180822](https://github.com/MarshalX/yandex2spotify/assets/76998547/e18529e2-6a22-431c-9141-5079335efd3b)

Кажись остановилось на этом плейлисте и этом треке.
https://music.yandex.ru/users/reagent992/playlists/1035
https://music.yandex.ru/album/4698900/track/37138319

Так же на Spotify не создались плейлисты с нестандартными названиями, в которых есть слеш( / ) или смайлик. 
Вроде этого:
https://music.yandex.ru/users/reagent992/playlists/1018 
Ну или это совпадение из-за того что скрипт завершил работу раньше.

Стоит запускать скрипт заново? Скрипт не создает дубликаты?

**Comment by MarshalX** [comment]
Насколько помню перезапуск дубликаты создаст. И не уверен что он поможет решить проблему. Нужно отлаживать и исправлять
